version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-adminpassword}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-trading_org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-trading}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-token}

  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-trading_org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-trading}
      - EXCHANGE_ID=${EXCHANGE_ID:-binance}
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY:-}
      - EXCHANGE_SECRET=${EXCHANGE_SECRET:-}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  influxdb-data:
